### ISSUE TITLE
Wrong CXX compiler path in toolchain.cmake.armel

### ISSUE THREAD

**Issue by fuine** [ev3dev/docker-cross#1]
in line 7 you set CXX compiler flag to:
`set (CMAKE_CXX_COMPILER /opt/cc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin/arm-linux-gnueabihf-g++)`
and i think it should be
`set (CMAKE_CXX_COMPILER /opt/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin/arm-linux-gnueabihf-g++)`
I'm not sure if this is a bug or a feature and so i haven't opened a PR yet, could you comment on that?

**Comment by dlech** [comment]
Looks like a bug to me.
